<div class="row" style="padding-left: 40px;">
    <form action="" method="get" class="bs-docs-example form-search">
        <select class="form-control" name="Grade">
        <option value="">--年级--</option>
        <?php foreach ($grade as $key => $value) {?>
        <option value="<?php echo($key);?>" <?php if($query['Grade']==$key) echo "selected";?>><?php echo($value);?></option>
        <?php }?>
        </select>
        <input class="form-control" name="Mobile" value="<?php echo $query['Mobile'];?>" placeholder="手机号"/>
        <input class="form-control" name="Name" value="<?php echo $query['Name'];?>" placeholder="姓名"/>
        <button type="submit"  class="btn btn-info">查询</button>
    </form>
</div>
<table width="100%" cellspacing="0" class="table table-bordered">
    <thead>
    <tr>
        <th width="30">姓名</th>
        <th width="30">手机号</th>
        <th width="30">Email</th>
        <th width="30">性别</th>
        <th width="30">年级</th>
        <th width="30">学校</th>
        <th width="30">账号激活</th>
        <th width="30">操作</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($memberList as $key => $val) { ?>
        <tr>
            <td align='center'><?php echo($val['Name']);?></td>
            <td align='center'><?php echo($val['Mobile']);?></td>
            <td align='center'><?php echo($val['Email']);?></td>
            <td align='center'><?php if($val['Gender']==1) echo "男";else echo "女";?></td>
            <td align='center'><?php echo($grade[$val['Grade']]);?></td>
            <td align='center'><?php echo($val['School']);?></td>
            <td align='center'><?php if($val['Activated']==1) echo "已激活";else echo "未激活";?></td>
            <td align='center'>
                <a href="/admin/classes/list?MemberID=<?php echo $val['MemberID']; ?>&Grade=<?php echo $val['Grade'];?>">推荐课程</a>
                <a href="/admin/classes/delete?ClassID=<?php echo $val['ClassID']; ?>" class="zajax" title="确定删除？">删除</a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php echo($pagination);?>
<script type="text/javascript">
    $(function(){
        var subjectList = new Array();
        <?php foreach ($subjectList as $key => $value) {?>
        subjectList["<?php echo $key;?>"] = new Array();
        <?php foreach ($value as $kk => $vv) {?>
        subjectList["<?php echo $key;?>"].push("<option value=<?php echo $vv['SubjectID']; ?>><?php echo $vv['Title'];?></option>"); 
        <?php }?>
        <?php }?>
        $(".zajax").zajax();
        $("select[name=Grade]").change(function(){
            $("select[name=SubjectID]").empty();
            $("select[name=SubjectID]").append("<option>--科目--</option>");
            var value = $(this).children('option:selected').val();
            var len = subjectList[value].length;
            for(var i = 0;i < len; i++){
                $("select[name=SubjectID]").append(subjectList[value][i]);
            }
        });
    })
</script>