<?php
/**
 * Created by PhpStorm.
 * User: zhangxiaohu01
 * Date: 15-3-15
 * Time: 下午2:09
 */

?>
<style>
    .checked{background-color: #76cc3d}

</style>
<div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">账号组列表</div>
    </div>
    <div class="block-content collapse in">
        <div class="span12">

            <div id="example2_wrapper" class="dataTables_wrapper form-inline" role="grid">

                <form action="/admin/group/info" method="post" id="article_form">
                    <fieldset>
                        <legend>编辑账号组</legend>

                        <div class="form-inline">
                            <label class="control-label" for="focusedInput">账号组名</label>
                            <input type="hidden" name="id" value="<?php if (isset($info)): echo $info['id']; endif;?>">
                            <input type="text" class="input-xlarge focused" name="group_name" id="group_name" value="<?php if (isset($info)): echo $info['group_name']; endif; ?>"/>
                            <button type="submit" class="btn">Submit</button>
                        </div>


                    </fieldset>

                    <fieldset>
                        <legend>管理权限</legend>

                    <div id="example2_wrapper" class="dataTables_wrapper form-inline" role="grid">

                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable"
                               id="example2" aria-describedby="example2_info">
                            <thead>
                            <tr role="row">
                                <th class="center" style="width: 45px;">
                                    <input type="checkbox" name="checkbox" onclick="$('input[type=checkbox]').attr('checked',$(this).attr('checked'))"/>
                                </th>
                                <th class="center">序号</th>
                                <th class="center">权限名称</th>
                            </tr>
                            </thead>

                            <tbody role="alert" aria-live="polite" aria-relevant="all">

                            <?php foreach($menu_list as $key =>$val): ?>
                            <tr <?php if ($val['parent_id'] == 0): echo 'class="info"'; endif; ?>>
                                <td <?php if (isset($info['menu_id'][$val['id']])){?> style="background-color: #76CC3D" <?php }?>>
                                    <input class="admin_<?php echo $val['id'];?> parent_id_<?php echo $val['parent_id'];?>" type="checkbox" value="<?php echo $val['id'];?>" name="menu_id[]" <?php if (isset($info['menu_id'][$val['id']])){?> checked<?php }?> date-id="<?php echo $val['id'];?>" onclick="select_checkbox(this)"/>
                                </td>
                                <td><?php echo $val['id'];?></td>
                                <td><?php echo $val['title'];?> (<?php echo $val['url'];?>)</td>
                            </tr>
                            <?php endforeach; ?>

                            </tbody>
                        </table>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">提交</button>
                        </div>

                    </div>

                   </fieldset>

                </form>



            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){


        /* 第三极菜单选中 */
        $(".menu3").click(function(){

            parent_id = $(this).attr('parent_id');
            parent = $("#"+parent_id);
            if ($(this).attr('checked') == false)
            {
                i = 0;
                $.each($('input[parent_id='+parent_id+']'),function(k,v){

                    if ($(v).attr('checked') == true)
                    {
                        i = 1;
                    }
                })

                if (i == 0)
                {
                    $(parent).attr('checked',false);
                    $("#"+$(parent).attr("parent_id")).attr('checked',false);
                }

            }
            else
            {
                $(parent).attr('checked',true);
                $("#"+$(parent).attr("parent_id")).attr('checked',true);
            }

        })

        /* 第二级选中 */
        $(".menu2").click(function(){
            obj2 = $(this);
            $.each($('input[parent_id='+$(this).attr('id')+']'),function(k,v){

                $(v).attr('checked',$(obj2).attr('checked'))
            })
        })

        /* 第三级选中 */
        $(".menu1").click(function(){

            obj1 = $(this);

            $.each($('input[parent_id='+$(this).attr('id')+']'),function(k,v){

                $(v).attr('checked',$(obj1).attr('checked')).click().attr('checked',$(obj1).attr('checked'));
            })
        })
    })
    function select_checkbox(obj)
    {
        /* 遍历 下级 */
        var id = $(obj).attr('date-id');
        var sid;
        $.each($(".parent_id_"+id),function(k,v){
            $(v).attr('checked',$(obj).attr('checked'));
            $.each($(".parent_id_"+$(v).attr('date-id')),function(kk,vv){
                $(vv).attr('checked',$(v).attr('checked'));
                $.each($(".parent_id_"+$(vv).attr('date-id')),function(kkk,vvv){
                    $(vvv).attr('checked',$(vv).attr('checked'));
                })
            })
        })
    }
</script>