<!DOCTYPE html>
<html>
<head>
    <title><?php echo $title; ?></title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    <link href="/bootstrap/css/styles.css" rel="stylesheet" media="screen">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <![endif]-->
</head>
<body id="modify">
<div class="container">
        <br>
    <p>温馨提示：系统初始密码为123456，用户可以重置密码，如果忘记密码，请联系管理员修改。</p>
    <form action="/admin/modify" method="post" class="form-signin" style="width:250px;">
        <br>
        <h4>修改密码</h4>
        <br>
        <input type="password" name="password" class="input-block-level" placeholder="密码">
        <input type="password" name="password1" class="input-block-level" placeholder="请重复输入密码">
        <button class="btn btn-large btn-primary" type="button" id="submit">提交</button>
    </form>

</div> <!-- /container -->
<script src="/js/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script>
$(function(){
  $("#submit").click(function(){
        $.ajax({
            type:'POST',
            url:"/admin/modify" ,
            data: {"password":$("input[name=password]").val(),"password1":$("input[name=password1]").val()} ,
            success: function(data){
                // console.log(data);
                alert(data.msg);
            } ,
            dataType:'json'
        });
  }) 
})
</script>
</body>
</html>