<?php
/**
 * Created by PhpStorm.
 * User: zhangxiaohu01
 * Date: 15-3-15
 * Time: 下午2:09
 */

?>

<!-- block -->
<div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">管理员列表</div>
    </div>
    <div class="block-content collapse in">
        <div class="span12">

            <div id="example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                <div class="row" style="padding-left: 40px;">
                    <form action="/admin/user/list" method="get" class="bs-docs-example form-search">
                        <input type="text" name="username" class="input-medium search-query" value="<?php echo $username;?>">
                        <button type="submit" class="btn btn-info">Search</button>
                    </form>
                </div>
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable">
                    <thead>

                    <th class="center">#</th>
                    <th class="center">帐号</th>
                    <th class="center">所在组</th>
                    <th class="center">所属项目</th>
                    <th class="center">登录IP</th>
                    <th class="center">登录时间</th>
                    <th class="center">操作</th>

                    </thead>

                    <tbody>
                    <?php foreach ($list as $key => $val): //var_dump($val);?>
                    <tr class="gradeA <?php if ($key % 2 == 0): echo 'even'; else: echo 'odd'; endif;?>">
                        <td class="center">
                            <?php echo $val['id'];?>
                        </td>
                        <td class="center">
                            <?php echo $val['username'];?>
                        </td>
                        <td class="center">
                            <?php echo $val['group'];?>
                        </td>
                        <td class="center">
                            <?php echo $val['project'];?>
                        </td>
                        <td class="center">
                            <?php echo $val['login_ip'];?>
                        </td>
                        <td class="center">
                            <?php echo $val['logintime'];?>
                        </td>
                        <td class="center">
                            <a href="/admin/user/edit?id=<?php echo $val['id'];?>&url=<?php echo $url;?>" style="margin-left: 10px">编辑</a>
                            <a href="/admin/user/delete?id=<?php echo $val['id'];?>" style="margin-left: 10px" class="zajax" title="确定要删除吗?">删除</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>

                    </tbody>
                </table>
                <div class="row">
                        <?=$page?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /block -->

<script type="text/javascript">
    $(function(){
        $(".zajax").zajax();
    })
</script>
