<!DOCTYPE html>
<html>
<head>
    <title></title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    <link href="/bootstrap/css/styles.css" rel="stylesheet" media="screen">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <![endif]-->
</head>
<body id="login">
	<div style="margin-left:30px;">
	<h6>新用户须知:</h6>
	<p>1.新用户密码为123456，请点击上方“重置密码”按钮充值密码。</p>
	<p>2.如果用户忘记密码，请联系系统管理员重置密码。</p>
	<p>3.如果用户使用过程中有些功能因为权限不足而无法操作，请联系管理员申请对应权限。</p>
	</div>
</body>
<script src="/js/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
</html>