<div class="row" style="padding-left: 40px;">
    <form action="" method="get" class="bs-docs-example form-search">
        <select class="form-control" name="Grade">
        <option value="">--年级--</option>
        <?php foreach ($grade as $key => $value) {?>
        <option value="<?php echo($key);?>" <?php if($query['Grade']==$key) echo "selected";?>><?php echo($value);?></option>
        <?php }?>
        </select>
        <select class="form-control" name="SubjectID">
            <option value="">--科目--</option>
            <?php foreach ($subjectList[$query['Grade']] as $key => $value) {?>
                <option value="<?php echo $value['SubjectID'];?>" <?php if($value['SubjectID']==$query['SubjectID']) echo "selected";?>><?php echo $value['Title'];?></option>
            <?php }?>        
        </select>
        <button type="submit"  class="btn btn-info">查询</button>
    </form>
</div>
<table width="100%" cellspacing="0" class="table table-bordered">
    <thead>
    <tr>
        <th width="30">年级</th>
        <th width="30">科目</th>
        <th width="30">章节</th>
        <th width="30">标题</th>
        <th width="30">操作</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($ChapterList as $key => $val) { ?>
        <tr>
            <td align='center'><?php echo($grade[$val['Grade']]);?></td>
            <td align='center'><?php foreach($subjectList[$val['Grade']] as $value){
                if($value['SubjectID']==$val['SubjectID']) echo $value['Title'];
            }?></td>
            <td align='center'><?php echo($val['Chapter']);?></td>
            <td align='center'><?php echo($val['Title']);?></td>
            <td align='center'><a href="/admin/chapter/delete?ChapterID=<?php echo $val['ChapterID']; ?>" class="zajax" title="确定删除？">删除</a></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php echo($pagination);?>
<script type="text/javascript">
    $(function(){
        var subjectList = new Array();
        <?php foreach ($subjectList as $key => $value) {?>
        subjectList["<?php echo $key;?>"] = new Array();
        <?php foreach ($value as $kk => $vv) {?>
        subjectList["<?php echo $key;?>"].push("<option value=<?php echo $vv['SubjectID']; ?>><?php echo $vv['Title'];?></option>"); 
        <?php }?>
        <?php }?>
        $(".zajax").zajax();
        $("select[name=Grade]").change(function(){
            $("select[name=SubjectID]").empty();
            $("select[name=SubjectID]").append("<option>--科目--</option>");
            var value = $(this).children('option:selected').val();
            var len = subjectList[value].length;
            for(var i = 0;i < len; i++){
                $("select[name=SubjectID]").append(subjectList[value][i]);
            }
        });
    })
</script>