<div class="row" style="padding-left: 40px;">
    <form action="" method="get" class="bs-docs-example form-search">
        <select class="form-control" name="grade">
        <option value=""></option>
        <?php foreach ($grade as $key => $value) {?>
        <option value="<?php echo($key);?>"><?php echo($value);?></option>
        <?php }?>
        </select>
        <button type="submit"  class="btn btn-info">查询</button>
    </form>
</div>
<table width="100%" cellspacing="0" class="table table-bordered">
    <thead>
    <tr>
        <th width="30">编号</th>
        <th width="30">年级</th>
        <th width="30">科目</th>
        <th width="30">图片</th>
        <th width="30">视频</th>
        <th width="30">价格</th>
        <th width="30">操作</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($classList as $key => $val) { ?>
        <tr>
            <td align='center'><?php echo($val['ClassNo']);?></td>
            <td align='center'><?php echo($grade[$val['Grade']]);?></td>
            <td align='center'><?php echo($val['SubjectID']);?></td>
            <td align='center'><a href='<?php echo('\resource\Image'.'\\'.$val['Image']);?>' target="_Blank">图片</a></td>
            <td align='center'><a href='<?php echo('\resource\Video'.'\\'.$val['Video']);?>' target="_Blank">视频</a></td>
            <td align='center'><?php echo($val['Price']);?></td>
            <td align='center'>
                <a href="/admin/classes/edit?ClassID=<?php echo $val['ClassID']; ?>">编辑</a>
                <a href="/admin/classes/delete?ClassID=<?php echo $val['ClassID']; ?>" class="zajax" title="确定删除？">删除</a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php echo($pagination);?>
<script type="text/javascript">
    $(function(){
        $(".zajax").zajax();
    })
</script>