<form action="/admin/subject/info" id="subjectForm" method="post">
<table width="100%" cellspacing="0" class="table table-bordered">
    <tbody>
        <tr>
            <th width="30">年级</th>
            <td width="80">
                <select name='Grade'>
                    <?php foreach ($grade as $key => $value) {?>
                        <option value="<?php echo($key);?>"><?php echo($value);?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr>
            <th width="30">科目</th>
            <td width="80">
                <select name='SubjectType'>
                        <option value=""></option>
                    <?php foreach ($subject as $key => $value) {?>
                        <option value="<?php echo($key);?>"><?php echo($value);?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
    </tbody>
</table>
<div class="form-actions">
    <button type="submit" class="btn btn-primary">提交</button>
</div>
</form>
<script>
    $(function(){
        $("#subjectForm").z_form_submit({url:"/admin/subject/list"});
    })
</script>