<table width="100%" cellspacing="0" class="table table-bordered">
    <tbody>
        <tr>
            <th width="30">年级</th>
            <td width="80">
                <select name='Grade'>
                    <?php foreach ($grade as $key => $value) {?>
                        <option value="<?php echo($key);?>"><?php echo($value);?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr>
            <th width="30">科目</th>
            <td width="80"><input type="text" name="Title"/></td>
        </tr>
    </tbody>
</table>