<!DOCTYPE html>
<html>
<head>
    <title><?php echo $title; ?></title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    <link href="/bootstrap/css/styles.css" rel="stylesheet" media="screen">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <![endif]-->
</head>
<body id="login">
<div class="container">

    <form action="/admin/login" method="post" class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" name="username" class="input-block-level" placeholder="账号">
        <input type="password" name="password" class="input-block-level" placeholder="密码">
        <button class="btn btn-large btn-primary" type="button" id="signIn">Sign in</button>
    </form>

</div> <!-- /container -->
<script src="/js/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script>
$(function(){
  $("#signIn").click(function(){
        $.ajax({
            type:'POST',
            url:"/admin/login" ,
            data: {"username":$("input[name=username]").val(),"password":$("input[name=password]").val()} ,
            success: function(data){
                if(data.status==-1){
                    alert(data.msg);
                }else if(data.status==0){
                    window.location.href = data.data.callback;
                }
            } ,
            dataType:'json'
        });
  }) 
})
</script>
</body>
</html>