<style type="text/css">
.opacity {opacity:0;FILTER:Alpha(Opacity=0);}
.text {border: 1px solid #c0c1b3;}
.text.opacity {position:absolute;height:20px;}
.text.file {width:129px!important;width:135px;z-index:100;}
.text.file_btn {height:19px;margin:0 0 -1px 0;width:auto!important;width:60px;background:#f0f0f0;padding:;}
</style>
<form action="/admin/classes/info" id="classesForm" method="post" enctype="multipart/form-data">
<table width="100%" cellspacing="0" class="table table-bordered">
    <tbody>
        <input type="hidden" name="ClassID" value="<?php echo($info['ClassID'])?>"/>
        <tr>
            <th width="30">课程编号</th>
            <td width="80"><input type="text" name="ClassNo"  value="<?php echo($info['ClassNo'])?>"/></td>
        </tr>
        <tr>
            <th width="30">年级</th>
            <td width="80">
                <select name='Grade'>
                    <option></option>
                    <?php foreach ($grade as $key => $value) {?>
                        <option value="<?php echo($key);?>" <?php if($key==$info['Grade']) echo "selected"?>><?php echo($value);?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr>
            <th width="30">科目</th>
            <td width="80">
                <select name="SubjectID">
                    <?php foreach ($subjectList[$info['Grade']] as $key => $value) {?>
                        <option value="<?php echo $value['SubjectID'];?>" <?php if($value['SubjectID']==$info['SubjectID']) echo "selected";?>><?php echo $value['Title'];?></option>
                    <?php }?>
                </select>
            </td>
        </tr>
        <tr>
            <th width="30">图片</th>
            <td width="80">
                <input type="file" name="Image" size="20" onchange="document.getElementById('file_0').value=this.value" class="text opacity">
                <input name="file_0" id="file_0" value="<?php echo $info['Image']; ?>" class="text"> 
                <input type="button" value="浏览..." class="file_btn">
            </td>
        </tr>
        <tr>
            <th width="30">视频</th>
            <td width="80">
                <input type="file" name="Video" size="20" onchange="document.getElementById('file_1').value=this.value" class="text opacity">
                <input name="file_1" id="file_1" value="<?php echo $info['Video']; ?>" class="text"> 
                <input type="button" value="浏览..." class="file_btn">
            </td>
        </tr>
        <tr>
            <th width="30">价格</th>
            <td width="80"><input type="text" name="Price"  value="<?php echo($info['Price'])?>"/></td>
            </td>
        </tr>
    </tbody>
</table>
<div class="form-actions">
    <button type="submit" class="btn btn-primary">提交</button>
</div>
</form>
<script type="text/javascript">
$(function(){
    var subjectList = new Array();
    <?php foreach ($subjectList as $key => $value) {?>
    subjectList["<?php echo $key;?>"] = new Array();
    <?php foreach ($value as $kk => $vv) {?>
    subjectList["<?php echo $key;?>"].push("<option value=<?php echo $vv['SubjectID']; ?>><?php echo $vv['Title'];?></option>"); 
    <?php }?>
    <?php }?>
    $("#classesForm").ajaxForm({
        //定义返回JSON数据，还包括xml和script格式
        dataType:'json',
        beforeSend: function() {
            //表单提交前做表单验证
        },
        success: function(data) {
            console.log(data);return;
            //提交成功后调用
            if (data.status == 1)
            {
                tb_tips_url(data.msg,'/admin/classes/list',1000);
            }
            else if (2 == data.status)
            {
                opts.call_fun && opts.call_fun();
                $(obj).find('input').attr('disabled',false);
            }
            else
            {
                tips(opts,data.msg,false);
                $(obj).find('input').attr('disabled',false);
            }
        }
    });
    $("select[name=Grade]").change(function(){
        $("select[name=SubjectID]").empty();
        var value = $(this).children('option:selected').val();
        var len = subjectList[value].length;
        for(var i = 0;i < len; i++){
            $("select[name=SubjectID]").append(subjectList[value][i]);
        }
    });
});
</script>