<?php
/**
 * Created by PhpStorm.
 * User: zhangxiaohu01
 * Date: 15-3-15
 * Time: 下午2:09
 */

?>

<div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">账号组列表</div>
    </div>
    <div class="block-content collapse in">
        <div class="span12">


            <div id="example2_wrapper" class="dataTables_wrapper form-inline" role="grid">

                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable"
                       id="example2" aria-describedby="example2_info">
                    <thead>
                    <tr role="row">
                        <th></th>
                        <th class="center" style="width: 60px;">序号</th>
                        <th class="center">账号组</th>
                        <th class="center">操作</th>
                    </tr>
                    </thead>

                    <tbody role="alert" aria-live="polite" aria-relevant="all">

                    <?php foreach($list as $key =>$val): ?>
                    <tr class="gradeA <?php if ($key % 2 == 0): echo 'even'; else: echo 'odd'; endif;?>">
                        <td>
                            <input type="checkbox" value="<?php echo $val['id'];?>" name="id[]">
                        </td>
                        <td><?php echo $val['id'];?></td>
                        <td><?php echo $val['group_name'];?></td>
                        <td>
                            <a style="margin-left: 10px" href="/admin/group/edit?id=<?php echo $val['id'];?>">编辑</a>
                            <a style="margin-left: 10px" href="/admin/group/delete?id=<?php echo $val['id'];?>" title="确定删除删除吗?" class="zajax">删除</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        $(".zajax").zajax();
    })
</script>